version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"  # Χρησιμοποίησε μια διαφορετική εξωτερική θύρα
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins

  mock_api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5000:8080"
    container_name: mock_api

volumes:
  jenkins_home:

