services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"  # Χρησιμοποίησε μια διαφορετική εξωτερική θύρα για Jenkins
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins
    networks:
      - ci_network

  mock_api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5000:8080"
    container_name: mock_api
    networks:
      - ci_network

  sonarqube:
    image: sonarqube:9.9.0-community
    ports:
      - "9000:9000"
    container_name: sonarqube
    networks:
      - ci_network
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    networks:
      - ci_network

  trivy:
    image: aquasec/trivy:latest
    entrypoint: [ "sleep", "infinity" ]
    container_name: trivy
    networks:
      - ci_network

  nmap:
    image: instrumentisto/nmap:latest
    entrypoint: [ "sleep", "infinity" ]
    container_name: nmap
    networks:
      - ci_network

  zap:
    image: zaproxy/zap-stable
    entrypoint: [ "sleep", "infinity" ]
    container_name: zap
    networks:
      - ci_network

  trufflehog:
    image: trufflesecurity/trufflehog:latest
    entrypoint: [ "sleep", "infinity" ]
    container_name: trufflehog
    networks:
      - ci_network

volumes:
  jenkins_home:
  sonarqube_db:

networks:
  ci_network:
    driver: bridge

